-- union, except, intersect
CREATE DATABASE teste;
USE teste;

CREATE TABLE R(
	a CHAR(2)
);
CREATE TABLE S(
	a CHAR(2)
);

INSERT INTO R(a)
VALUES ('a1'),('a2'),('a2'),('a3');

INSERT INTO S(a)
VALUES ('a1'),('a1'),('a2'),('a3'),('a4'),('a5');

SELECT * FROM R;
SELECT * FROM S;

-- EXCEPT -> NOT IN
SELECT * FROM S WHERE a NOT IN (SELECT * FROM R);

-- UNION
SELECT DISTINCT R.a FROM R UNION SELECT DISTINCT S.a FROM S;
SELECT DISTINCT * FROM R UNION SELECT DISTINCT * FROM S;

-- INTERSECT
SELECT DISTINCT R.a FROM R WHERE R.a IN (SELECT S.a FROM S);
SELECT DISTINCT * FROM R WHERE a IN (SELECT * FROM S);